# Created: 2020/10/14 19:00:21
# Last modified: 2020/10/30 23:37:20

name: Publish

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          ref: main # based on https://github.com/actions/checkout/issues/136

      - name: Changed Files Exporter
        id: changed-files
        uses: futuratrepadeira/changed-files@v3.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '^.*\.(md|markdown)$'
          result-encoding: 'string'

      - name: Run marp-action setup
        id: marp-action
        uses: aheil/marp-action@v1.1.0-beta
        with:
          src-dir: 'slides'
          src-files: ${{ steps.changed-files.outputs.files_updated }}