# Created: 2020/10/14 19:00:21
# Last modified: 2020/10/30 23:20:59

name: Publish

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Changed Files Exporter
        id: changed-files
        uses: futuratrepadeira/changed-files@v3.3.0
        with:
          repo-token: ${{ github.token }}
          pattern: '^.*\.(md|markdown)$'
          result-encoding: 'string'

      - name: Run marp-action setup
        id: marp-action
        uses: aheil/marp-action@v1.1.0-beta
        with:
          src-dir: 'slides'
          src-files: ${{ steps.changed-files.outputs.files_updated }}

          https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action/61236803#61236803